services:
#######################
##### RPC & TOPIC #####
#######################
    # Bonus RPC
    game.bonus.rpc:
        class: BonusBundle\RPC\BonusRpc
        arguments:
            - "@gos_web_socket.websocket.client_manipulator"
            - "@doctrine.orm.entity_manager"
            - "@bonus.registry"
        tags:
            - { name: gos_web_socket.rpc }

    # Bonus Topic
    game.bonus.topic:
        class: BonusBundle\Topic\BonusTopic
        arguments:
            - "@gos_web_socket.websocket.client_manipulator"
        tags:
            - { name: gos_web_socket.topic }
###############################
##### REGISTRY & MANAGER ######
###############################
    # The weapon registry
    weapon.registry:
        class: BonusBundle\Manager\WeaponRegistry

    # The bonus registry
    bonus.registry:
        class: BonusBundle\Manager\BonusRegistry
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gos_web_socket.zmq.pusher"
            - "@event_dispatcher"

####################
##### WEAPONS ######
####################
    # Bomber
    weapon.bomber:
        class: BonusBundle\Weapons\BomberWeapon
        tags:
            - { name: weapon.type }

    # Flash
    weapon.flash:
        class: BonusBundle\Weapons\FlashWeapon
        tags:
            - { name: weapon.type }

    # Gust
    weapon.gust:
        class: BonusBundle\Weapons\GustWeapon
        tags:
            - { name: weapon.type }

    # Mortar
    weapon.mortar:
        class: BonusBundle\Weapons\MortarWeapon
        tags:
            - { name: weapon.type }

#################
##### BONUS #####
#################
    # Point bonus
    bonus.point:
        class: BonusBundle\Bonus\PointBonus
        tags:
            - { name: bonus.type }

    # Team point
    bonus.team_point:
        class: BonusBundle\Bonus\PointTeamBonus
        tags:
            - { name: bonus.type }

    # Skip player
    bonus.skip_player:
        class: BonusBundle\Bonus\SkipPlayer
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: bonus.type }
